name: Daily Commit

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit a timestamp
        run: |
          echo "Daily commit $(date)" >> daily_commit.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_commit.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"
          git push
